"""
Manages the initial placement phase of the Catan game.
Includes human guidance for settlement + road placement and confirmation.
This module defines the InitialPlacement class, handling the placement sequence for
4 AI players (settlement + road in rounds -2 and -1) using specified algorithms.
"""
import pygame
import random
from typing import Dict, List, Tuple, Optional, Set

from core.game import Game, Player
from core.board import Board
from core.constants import (
    NUM_PLAYERS, HUMAN_PLAYER, HP_ID,
    ResourceCard, TERRAIN_TO_RESOURCE, RESOURCE_ORDER,
    FNFREQ, FILENAME_FREQ, MG, FILENAME_MG
)
from gui.gui_human_player import GUIHumanPlayer
from gui.gui_guidance import PlacementState

from core.algorithms_initial_placement import InitialPlacementStrategies


class InitialPlacement:
    """Manages the initial placement phase for the Catan game."""

    def __init__(self, game: Game) -> None:
        """Manages the initial placement phase of the Catan game."""
        self.game = game

        if NUM_PLAYERS not in (2, 3, 4):
            raise ValueError(f"NUM_PLAYERS must be 2, 3 or 4 — got {NUM_PLAYERS}")

        self.num_players = NUM_PLAYERS
        player_ids = list(range(1, NUM_PLAYERS + 1))

        # Default algorithm can still be overridden per player
        self.player_algorithms: Dict[int, int] = {pid: 1 for pid in player_ids}

        self.sequence = player_ids + list(reversed(player_ids))
        self.current_step = 0

    def run(self) -> None:
        if FNFREQ == "Y":
            with open(FILENAME_FREQ, "a") as f:
                f.write(f"{self.game.id} | {self.game.state} | initial_placement.py | run\n")

        self.game.phase = "InitialPlacement"
        self.game.round = -2
        self.game.turn = 1
        self.game.board.round = self.game.round

        self.current_step = 0

        print("Initial Placement started. Use Play button to advance turns (including human P3).")

    def advance_turn(self) -> None:

        if FNFREQ == "Y":
            with open(FILENAME_FREQ, "a", encoding="utf-8") as f:
                f.write(f"{self.game.id} | {self.game.state} | initial_placement.py | advance_turn\n")

        if self.current_step >= len(self.sequence):
            self.game.phase = "Execution"
            self.game.game_over = True
            self.game.sync_round_turn()

            # Save a complete game snapshot after the initial placement phase.
            # The file name is generated by Game.save_game(), e.g.:
            # Saved_Game_23_Apr_2025_09_53_50_R2T1.txt
            saved_game_name = self.game.save_game()
            if MG:
                with open(FILENAME_MG, "a", encoding="utf-8") as f:
                    f.write(f"initial_placement.py | saved game after initial placement: {saved_game_name}\n")

            self.game.save_screenshot()
            return

        player_id = self.sequence[self.current_step]
        player = next(p for p in self.game.players if p.id == player_id)

        is_human_initial_turn = (
            HUMAN_PLAYER
            and player_id in HP_ID
            and self.game.round < 0
        )

        # Always disable PLAY while this turn is being processed.
        GUIHumanPlayer.button_next_turn2(self.game.gui, self.game, active=False)
        pygame.display.update()

        # === PLACEMENT ===
        if is_human_initial_turn:
            self.game.gui.human_guidance.start_settlement_phase(player)
        else:
            # AI: full placement strategy (settlement + road + resources if round -1)
            self.execute_initial_placement_strategy(player)

        # === COMMON UPDATE BLOCK ===
        self.game.gui.update_round_turn(self.game, special=False)
        self.game.gui.update_board(self.game.board, "Last")
        self.game.gui.update_scoreboard(self.game)
        pygame.display.update()

        self.current_step += 1
        self.game.advance_turn()

        # Re-enable PLAY only after AI / Markov has fully placed settlement + road.
        # For human turns, HumanGuidance._finish_human_turn() already enables it.
        if not is_human_initial_turn and self.game.phase == "InitialPlacement":
            GUIHumanPlayer.button_next_turn2(self.game.gui, self.game, active=True)
            pygame.display.update()


    def _emit_initial_placement_event(self, player: Player, message: str, *, update: bool = True) -> None:
        """Emit one visible Events/Twitter line for initial placement.

        The normal execution phase already writes messages through
        Game.emit_twitter_event(). Initial placement used to write only to the
        MG debug file, so this helper keeps the visible event feed in sync
        without making initial-placement logic depend on one GUI shape.
        """
        player_id = getattr(player, "id", None)

        try:
            if hasattr(self.game, "emit_twitter_event"):
                try:
                    self.game.emit_twitter_event(player_id, message, update=update)
                except TypeError:
                    self.game.emit_twitter_event(player_id, message)
                return

            gui = getattr(self.game, "gui", None)
            if gui is None:
                return

            if hasattr(gui, "add_tweet"):
                try:
                    gui.add_tweet(player_id, message, update=update)
                except TypeError:
                    gui.add_tweet(player_id, message)
                return

            if not hasattr(gui, "twitter") or not isinstance(getattr(gui, "twitter", None), list):
                gui.twitter = []
            gui.twitter.append([player_id, message])
            if update and hasattr(gui, "update_twitter"):
                gui.update_twitter()
        except Exception:
            # The visible event feed must never break initial placement.
            pass

    @staticmethod
    def _resource_label(resource: ResourceCard) -> str:
        """Return a readable resource name for enum/string resources."""
        value = getattr(resource, "value", resource)
        return str(value)

    def _format_resource_counts_for_event(self, resource_counts: List[int]) -> str:
        """Format starting resources as '+1 Wheat, +1 Wood, ...'."""
        parts: List[str] = []
        for resource, count in zip(RESOURCE_ORDER, resource_counts):
            if int(count) > 0:
                parts.append(f"+{int(count)} {self._resource_label(resource)}")
        return ", ".join(parts) if parts else "none"

    def record_initial_settlement_event(self, player: Player, intersection_id: int) -> None:
        """Show an initial-placement settlement in the visible Events pane."""
        self._emit_initial_placement_event(
            player,
            f"placed initial settlement at {int(intersection_id)}",
        )

    def record_initial_road_event(self, player: Player, road: Tuple[int, int]) -> None:
        """Show an initial-placement road in the visible Events pane."""
        road_label = list(tuple(sorted(int(x) for x in road)))
        self._emit_initial_placement_event(
            player,
            f"placed initial road at {road_label}",
        )

    def record_initial_resources_event(self, player: Player, resource_counts: List[int]) -> None:
        """Show starting resources from the second initial settlement."""
        if not any(int(x) > 0 for x in resource_counts):
            return
        self._emit_initial_placement_event(
            player,
            f"receives {self._format_resource_counts_for_event(resource_counts)}",
        )

    def execute_initial_placement_strategy(self, player: Player) -> None:
        """
        Execute the full AI initial placement strategy for one turn:
          - choose & place settlement
          - distribute resources (if round == -1)
          - choose & place road (connected to the last settlement, using strategic functions)
        """
        board = self.game.board
        algorithm_id = player.initial_placement_algorithm

        # 1. Choose best settlement location
        intersection_id, valid_intersections = self._choose_settlement_location(player, algorithm_id)

        # Place settlement on board
        board.occupy_intersection(
            intersection_id, "Settlement", player.color,
            placement_step=self.current_step
        )

        # Explicitly update player's settlements list
        player.settlements.append(intersection_id)
        self.record_initial_settlement_event(player, intersection_id)

        self.game.gui.update_scoreboard(self.game)
        
        if MG:
            with open(FILENAME_MG, "a", encoding="utf-8") as f:
                f.write(f"Initial placement | Player {player.id} ({player.color}) "
                        f"placed settlement at {intersection_id} (step={self.current_step})\n")

        # Distribute starting resources if second placement (round -1)
        if self.game.round == -1:
            self.distribute_initial_resources(intersection_id, player)

        # ────────────────────────────────────────────────
        # Road placement — connected to the last settlement + strategic choice
        # ────────────────────────────────────────────────
        last_settlement = player.settlements[-1]

        # Minimal blocked_tws: only already occupied intersections
        selected_tws = [
            i for i in range(len(board.intersections))
            if board.intersections[i] and board.intersections[i].occupied_tf
        ]
        blocked_tws = selected_tws[:]

        top_tws = []

        player_has_port_now = player.has_port()

        if player_has_port_now:
            best_road = InitialPlacementStrategies.find_best_road_missing_port(
                board=board,
                settlement_id=last_settlement,
                player=player,
                top_tws=top_tws,
                blocked_tws=blocked_tws,
                selected_tws=selected_tws
            )
        else:
            best_road = InitialPlacementStrategies.find_best_road_missing_port(
                board=board,
                settlement_id=last_settlement,
                player=player,
                top_tws=top_tws,
                blocked_tws=blocked_tws,
                selected_tws=selected_tws
            )

        if best_road:
            board.occupy_road(
                list(best_road), "Road", player.color,
                placement_step=self.current_step
            )
            player.roads.append(tuple(sorted(best_road)))
            self.record_initial_road_event(player, tuple(sorted(best_road)))

            if MG:
                with open(FILENAME_MG, "a", encoding="utf-8") as f:
                    f.write(f"Player {player.id} | round {self.game.round} | "
                            f"placed strategic road {best_road} from settlement {last_settlement} "
                            f"(has_port_now={player_has_port_now})\n")
        else:
            if MG:
                with open(FILENAME_MG, "a", encoding="utf-8") as f:
                    f.write(f"Warning: No valid road found for player {player.id} "
                            f"at settlement {last_settlement} (has_port={player_has_port_now})\n")

    def _get_valid_second_settlement_locations(self, player: Player) -> List[int]:
        """Return all intersections still valid for the second settlement in round -1."""
        valid = []
        for inter in self.game.board.intersections:
            if inter is None or inter.id in self.game.board.INTERSECTION_IN_WATER:
                continue
            if inter.occupied_tf:
                continue
            if not inter.can_build_tf:
                continue
            valid.append(inter.id)
        return valid

    def _choose_settlement_location(self, player: Player, algorithm_id: int) -> Tuple[int, List[int]]:
        """
        Select the initial settlement location using the configured algorithm.

        Algorithm numbering:
            1 = pips/trading, ports ignored
            2 = pips/trading, ports relevant
            3 = five-strategy engine
            4 = Markov
            5 = Expected-Hand feasibility / EH

        Behavior:
            - Algorithms 1, 2, 3, and 5 are handled through
            InitialPlacementStrategies.select_intersection().
            - Algorithm 4 is handled here because Markov needs a special candidate
            preselection and scoring flow.

        Markov behavior:
            - round -2: analyze top 8 candidates from _rank_by_pips_and_optional_port().
            - round -1: analyze top 12 candidates from _rank_by_pips_and_optional_port(),
            ordered by complementarity/reachability before Markov scoring.

        EH behavior:
            - algorithm 5 is intentionally treated as a normal non-Markov algorithm.
            - The EH calculation itself lives in core/algorithms_initial_placement.py.
        """
        if FNFREQ == "Y":
            with open(FILENAME_FREQ, "a") as f:
                f.write(
                    f"initial_placement.py | _choose_settlement_location | "
                    f"player {player.id} | algo={algorithm_id} | round={self.game.round}\n"
                )

        # ────────────────────────────────────────────────
        # Non-Markov behavior: algorithms 1, 2, 3, and 5
        # ────────────────────────────────────────────────
        if algorithm_id != 4:
            valid_intersections = [
                i for i in range(len(self.game.board.intersections))
                if self.game.can_build_intersection_tf(i)
            ]

            if not valid_intersections:
                fallback = [
                    i for i in range(len(self.game.board.intersections))
                    if getattr(self.game.board.intersections[i], "canbuildYNX", "N") != "X"
                ]
                if fallback:
                    return fallback[0], fallback
                return -1, []

            # Keep the legacy round -1 complementarity behavior only for algorithm 3.
            # EH / algorithm 5 must use its own feasibility logic in
            # InitialPlacementStrategies.select_intersection().
            if self.game.round == -1 and algorithm_id == 3:
                chosen = self._select_with_complementarity(
                    player,
                    valid_intersections,
                    algorithm_id,
                )
            else:
                chosen = InitialPlacementStrategies.select_intersection(
                    board=self.game.board,
                    player=player,
                    algorithm_id=algorithm_id,
                    valid_intersections=valid_intersections,
                    game_round=self.game.round,
                )

            return chosen, valid_intersections

        # ────────────────────────────────────────────────
        # Small local helpers for Markov candidate quality
        # ────────────────────────────────────────────────
        def _initial_resource_hand_from_intersection(inter_id: int) -> List[int]:
            """
            Simulate starting resources from a second settlement.

            Game order:
                [Wheat, Ore, Wood, Brick, Sheep]
            """
            board = self.game.board
            hand = [0, 0, 0, 0, 0]

            if inter_id < 0 or inter_id >= len(board.intersections):
                return hand

            inter = board.intersections[inter_id]
            if inter is None:
                return hand

            terrain_to_idx = {
                "Field": 0,      # Wheat
                "Mountain": 1,   # Ore
                "Forest": 2,     # Wood
                "Hill": 3,       # Brick
                "Pasture": 4,    # Sheep
            }

            for tile_id in getattr(inter, "three_tile_ids", []):
                if not (0 <= tile_id < len(board.tiles)):
                    continue

                tile = board.tiles[tile_id]
                if tile is None or tile.type in ("Sea", "Desert"):
                    continue

                idx = terrain_to_idx.get(tile.type)
                if idx is not None:
                    hand[idx] += 1

            return hand

        def _combined_game_order_pips(vertices: List[int]) -> List[float]:
            """
            Return combined pips in game order:
                [Wheat, Ore, Wood, Brick, Sheep]
            """
            board = self.game.board
            combined = [0.0, 0.0, 0.0, 0.0, 0.0]

            for vid in vertices:
                if not (0 <= vid < len(board.intersections)):
                    continue

                inter = board.intersections[vid]
                if inter is None:
                    continue

                pips = getattr(inter, "all_tile_pips", None)
                if not pips:
                    pips = getattr(inter, "three_tile_pips", [0.0] * 5)

                for i in range(min(5, len(pips))):
                    try:
                        combined[i] += float(pips[i])
                    except Exception:
                        pass

            return combined

        def _candidate_priority_round_minus1(candidate_id: int) -> Tuple:
            """
            Sort key for round -1 candidates inside the top-12 heuristic set.

            Target:
                settlement + 1 road = [1 Wheat, 0 Ore, 2 Wood, 2 Brick, 1 Sheep]

            Lower tuple is better.
            """
            board = self.game.board
            target = [1, 0, 2, 2, 1]  # [Wheat, Ore, Wood, Brick, Sheep]

            vertices = list(player.settlements) + [candidate_id]
            combined_pips = _combined_game_order_pips(vertices)
            init_hand = _initial_resource_hand_from_intersection(candidate_id)

            missing_count = 0
            useful_pips = 0.0
            useful_hand = 0

            for i, need in enumerate(target):
                if need <= 0:
                    continue

                already_have = init_hand[i] >= need
                can_produce = combined_pips[i] > 0.0

                if not already_have and not can_produce:
                    missing_count += 1
                else:
                    useful_pips += combined_pips[i]
                    useful_hand += min(init_hand[i], need)

            reachable_rank = 0 if missing_count == 0 else 1 if missing_count == 1 else 2

            inter = board.intersections[candidate_id]
            candidate_pips = 0.0
            candidate_coverage = 0
            port_bonus = 0

            if inter is not None:
                pips = getattr(inter, "all_tile_pips", None)
                if not pips:
                    pips = getattr(inter, "three_tile_pips", [0.0] * 5)

                candidate_pips = sum(float(x) for x in pips)
                candidate_coverage = sum(1 for x in pips if float(x) > 0.0)

                # Port is only a tie-breaker here. The candidate gate is still
                # _rank_by_pips_and_optional_port().
                if getattr(inter, "port_tf", False):
                    port_type = getattr(inter, "port_type", "").strip()
                    if port_type and port_type not in ("", "4:1", "Blank"):
                        port_bonus = 1

            total_coverage = sum(1 for x in combined_pips if float(x) > 0.0)

            return (
                reachable_rank,        # reachable candidates first
                missing_count,         # fewer impossible missing resources
                -useful_pips,          # more useful target pips
                -useful_hand,          # better immediate starting resources
                -total_coverage,       # broader total production
                -candidate_pips,       # stronger candidate
                -candidate_coverage,   # broader candidate
                -port_bonus,           # port as small tie-breaker only
                candidate_id,
            )

        def _ports_after_candidate(inter_id: int) -> Dict:
            """
            Keep compatibility with the Markov API.

            The current lean Markov evaluator does not anticipate trading, but
            this keeps real port information available for diagnostics or a
            later lightweight port tie-breaker.
            """
            player_ports = self.game.get_player_ports_dict(player).copy()
            inter = self.game.board.intersections[inter_id]

            if inter is not None and getattr(inter, "port_tf", False):
                port_type = getattr(inter, "port_type", "").strip()

                if port_type and port_type not in ("", "4:1", "Blank"):
                    if port_type == "3:1" or "3:1" in port_type:
                        player_ports["generic"] = 3
                    else:
                        res_name = port_type.split()[-1] if " " in port_type else port_type
                        if res_name.lower() in ("sheep", "wool"):
                            res_name = "Sheep"
                        player_ports[res_name] = 2

            return player_ports

        # ────────────────────────────────────────────────
        # Markov candidate selection
        # ────────────────────────────────────────────────
        if self.game.round == -2:
            all_valid = [
                i.id for i in self.game.board.intersections
                if i is not None and i.can_build_tf and not i.occupied_tf
            ]

            if not all_valid:
                return -1, []

            # Round -2: exactly top 8 by pips / optional-port heuristic.
            scores = InitialPlacementStrategies._rank_by_pips_and_optional_port(
                board=self.game.board,
                valid_intersections=all_valid,
                use_port=True,
            )
            ranked_all = [iid for iid, _, _, _ in scores]
            candidates = ranked_all[:8]

        else:
            all_valid = self._get_valid_second_settlement_locations(player)

            if not all_valid:
                return -1, []

            # Round -1: exactly top 12 by pips / optional-port heuristic.
            scores = InitialPlacementStrategies._rank_by_pips_and_optional_port(
                board=self.game.board,
                valid_intersections=all_valid,
                use_port=True,
            )
            ranked_all = [iid for iid, _, _, _ in scores]
            top_12 = ranked_all[:12]

            # Keep the candidate set limited to 12, but improve order within
            # that set before Markov scoring.
            candidates = sorted(top_12, key=_candidate_priority_round_minus1)

        if not candidates:
            return -1, all_valid

        # ────────────────────────────────────────────────
        # Markov scoring
        # ────────────────────────────────────────────────
        best_score = 9999.0
        best_inter = None
        tied_inters = []
        markov_scores = {}

        for inter_id in candidates:
            if self.game.round == -2:
                vertices = [inter_id]
            else:
                vertices = list(player.settlements) + [inter_id]

            # Do not pre-add second-settlement starting resources here.
            # MarkovEvaluator.get_expected_turns() adds them exactly once
            # through auto_initial_resources=True.
            hand = [0, 0, 0, 0, 0]
            player_ports = _ports_after_candidate(inter_id)

            try:
                score = self.game.markov.get_expected_turns(
                    vertices=vertices,
                    hand=hand,
                    player_ports=player_ports,
                )
            except Exception as e:
                if MG:
                    with open(FILENAME_MG, "a", encoding="utf-8") as f:
                        f.write(
                            f"initial_placement.py | Markov scoring error | "
                            f"player={player.id} inter={inter_id} vertices={vertices} error={e}\n"
                        )
                score = 9999.0

            if score is None:
                score = 9999.0

            try:
                score = float(score)
            except Exception:
                score = 9999.0

            markov_scores[inter_id] = score

            if score < best_score - 0.0001:
                best_score = score
                tied_inters = [inter_id]
                best_inter = inter_id
            elif abs(score - best_score) < 0.0001:
                tied_inters.append(inter_id)

        valid_scores = [
            s for s in markov_scores.values()
            if s is not None and s < 9999.0
        ]

        if best_inter is None:
            best_inter = candidates[0]

        elif not valid_scores:
            # If every candidate is effectively unreachable, use the ordered
            # candidate list rather than selecting randomly. In round -1 that
            # order includes complementarity/reachability; in round -2 it is
            # the pips/port heuristic order.
            best_inter = candidates[0]

        elif len(tied_inters) > 1:
            if self.game.round == -1:
                tie_set = set(tied_inters)
                for iid in candidates:
                    if iid in tie_set:
                        best_inter = iid
                        break
            else:
                best_inter = random.choice(tied_inters)

        if MG:
            with open(FILENAME_MG, "a", encoding="utf-8") as f:
                f.write(
                    f"initial_placement.py | Markov chose {best_inter} for player {player.id} "
                    f"round={self.game.round} best_score={best_score:.4f} "
                    f"candidates={candidates} scores={markov_scores}\n"
                )

        return best_inter, all_valid

    def _select_with_complementarity(
        self,
        player: Player,
        valid_intersections: List[int],
        algorithm_id: int = 3
    ) -> int:
        """
        Variant for round -1 that applies complementarity adjustment.
        """
        board = self.game.board

        base_id = InitialPlacementStrategies.select_intersection(
            board=board,
            player=player,
            algorithm_id=algorithm_id,
            valid_intersections=valid_intersections,
            game_round=self.game.round
        )

        current_pips = player.get_current_production_pips(board)

        candidates = []
        for inter_id in valid_intersections:
            raw = board.precomputed_pp_raw.get(inter_id)
            if not raw:
                continue

            if algorithm_id == 3 and hasattr(player, 'PP_balanced') and player.PP_balanced:
                max_strategy_score = max(
                    (entry[1] for pp_list in [
                        player.PP_balanced, player.PP_WB, player.PP_WO,
                        player.PP_WOS, player.PP_monopoly
                    ] for entry in pp_list if entry[0] == inter_id),
                    default=raw['tw_prob']
                )
            else:
                max_strategy_score = raw['tw_prob']

            new_probs = raw['three_probs']
            new_pips = [0.0] * 5
            for idx in range(5):
                if raw['three_types'][idx] > 0:
                    new_pips[idx] = new_probs[idx]

            multiplier = 1.0

            missing = sum(1 for p in current_pips if p < 2.0)
            added = sum(1 for i in range(5) if current_pips[i] < 2.0 and new_pips[i] > 1.5)

            if missing >= 2 and added >= 1:
                multiplier = 1.35

            wb_current = current_pips[2] + current_pips[3]
            wb_new = new_pips[2] + new_pips[3]
            if wb_current < 7.0 and wb_new > 5.0:
                multiplier = max(multiplier, 1.4)

            wo_current = current_pips[0] + current_pips[1]
            wo_new = new_pips[0] + new_pips[1]
            if wo_current < 6.0 and wo_new > 5.5:
                multiplier = max(multiplier, 1.5)

            overlap = sum(min(c, n) for c, n in zip(current_pips, new_pips))
            if overlap > 12.0:
                multiplier *= 0.65

            candidates.append((inter_id, max_strategy_score * multiplier))

        if not candidates:
            return base_id

        best_id = max(candidates, key=lambda x: x[1])[0]

        if MG:
            with open(FILENAME_MG, "a") as f:
                f.write(f"Round -1 complementarity | Player {player.id} (algo {algorithm_id}) "
                        f"chose {best_id} (base adjusted)\n")

        return best_id

    def distribute_initial_resources(self, intersection_id: int, player: Player) -> None:
        """Distribute initial resource cards from the second settlement placement."""
        intersection = self.game.board.intersections[intersection_id]
        if intersection is None:
            return

        resource_counts = [0] * len(RESOURCE_ORDER)

        for tile_id in intersection.three_tile_ids:
            tile = self.game.board.tiles[tile_id]
            if not tile or tile.type in ("Sea", "Desert"):
                continue

            resource = TERRAIN_TO_RESOURCE.get(tile.type)
            if resource:
                try:
                    idx = RESOURCE_ORDER.index(resource)
                    resource_counts[idx] += 1
                    player.add_rcard(resource, 1)
                except ValueError:
                    if MG:
                        with open(FILENAME_MG, "a") as f:
                            f.write(f"initial_placement.py | distribute_initial_resources | "
                                    f"Resource {resource} not found in RESOURCE_ORDER "
                                    f"(tile type was '{tile.type}')\n")

        player.number_of_rcards = sum(player.rcards.get(rc, 0) for rc in ResourceCard)

        player_id = player.id
        delta_rc = sum(resource_counts)

        self.game.update_strategy_dashboard(player)

        for dash in self.game.resource_card_dashboard:
            for i, count in enumerate(resource_counts):
                dash.resource_production_game_total[i] += count

            for p in dash.resource_production_game_player:
                if p[0] == player_id:
                    for i, count in enumerate(resource_counts):
                        p[i + 1] += count

            for view in dash.resource_production_game_player_view:
                if view[1] == player_id:
                    for i, count in enumerate(resource_counts):
                        view[i + 2] += count

        current_views = [
            [v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7], v[8], v[9]]
            for v in self.game.resource_card_dashboard[0].resource_production_game_player_view
        ]

        self.game.log_event([
            [1, f"RP_InitialPlacement: {intersection_id} for {player.color}"],
            [2, self.game.sequence_number],
            [3, self.game.round],
            [4, self.game.turn],
            [5, player.points],
            [6, 4],
            [7, 5 - len(player.settlements)],
            [8, 15 - len(player.roads)],
            [9, player.size_longest_route],
            [10, player.size_largest_army],
            [12, 0], [13, 0],
            [14, player.number_of_rcards],
            [15, 0],
            [16, intersection_id], [17, 0],
            [18, player_id], [19, 0],
            [20, "RP_InitialPlacement"],
            [21, "99999"], [22, "99999X99999"],
            [23, [resource_counts]],
            [24, delta_rc],
            [25, resource_counts],
            [26, [0, 0, 0, 0, 0]],
            [27, delta_rc],
            [28, current_views],
            [29, 0],
            [30, [0, 0, 0, 0, 0]],
            [31, [0, 0, 0, 0, 0]],
            [32, 0], [33, 0],
        ])

        self.record_initial_resources_event(player, resource_counts)

    def handle_click(self, pos: Tuple[int, int]) -> bool:
        guidance = self.game.gui.human_guidance

        if guidance.state == PlacementState.IDLE:
            return False

        handled = guidance.on_board_click(pos)
        if handled:
            return True

        return False
